name:                VargInterpreter
version:             1.0
github:              "Swordlash/Interpreter"
license:             BSD3
author:              "Mateusz Goślinowski"
maintainer:          "mateusz.goslinowski@gmail.com"
copyright:           "2018 Mateusz Goślinowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Swordlash/Varg#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - mtl
  - containers
  - ansi-terminal

default-extensions:
  - LambdaCase
  - FlexibleContexts
  - FlexibleInstances
  - TypeSynonymInstances
  - TupleSections


library:
  source-dirs:
    - src

executables:
  Varg:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VargInterpreter

tests:
  Interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - VargInterpreter
